version: '3'
services:
  mysql:
    container_name: wishlist_api_db
    image: mysql:8
    restart: always
    environment:
      MYSQL_DATABASE: wishlist
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306
    volumes:
      - db_data:/var/lib/mysql

  app:
    build:
    context: ./api
    container_name: wishlist_api
    depends_on:
      - mysql
    ports:
      - "9002:3000"
    environment:
      DATABASE_HOST: mysql
      DATABASE_USER: root
      DATABASE_PASSWORD: root
      DATABASE_NAME: wishlist

volumes:
  db_data: